language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO="1.5"
  - DJANGO="1.6"
  - DJANGO="1.7"
  - DJANGO="1.8"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="1.7"
    - python: "2.6"
      env: DJANGO="1.8"
install:
  - pip install -q Django==$DJANGO
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install importlib; fi
  - pip install pep8
  - pip install coveralls
  - pip install django-easysettings
  - pip install -q -e .
before_script:
  - "pep8 --ignore=E501,E225 password_policies"
script:
  - coverage run tests.py
after_success:
  coveralls
