language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO=">= 1.7,<1.8"
  - DJANGO=">= 1.8,<1.9"
  - DJANGO=">= 1.9,<1.10"
install:
  - pip install -q Django$DJANGO
  - pip install pep8
  - pip install coveralls
  - pip install django-easysettings
  - pip install -q -e .
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=">= 1.9,<1.10"
    - python: "3.5"
      env: DJANGO=">= 1.7,<1.8"
before_script:
  - "pep8 --ignore=E501,E225 password_policies"
script:
  - coverage run tests.py
after_success:
  coveralls
